/* SPDX-License-Identifier: GPL-2.0 */
#ifndef KFI_PROFILE_ANDROID13_5_15_H
#define KFI_PROFILE_ANDROID13_5_15_H

#define KFI_PROFILE_NAME "android13-5.15"
#define KFI_PROFILE_LINUX_MAJOR 5
#define KFI_PROFILE_LINUX_MINOR 15
#define KFI_PROFILE_ENFORCE_VERSION 1

#endif
