/* SPDX-License-Identifier: GPL-2.0 */
#ifndef KFI_PROFILE_ANDROID14_6_1_H
#define KFI_PROFILE_ANDROID14_6_1_H

#define KFI_PROFILE_NAME "android14-6.1"
#define KFI_PROFILE_LINUX_MAJOR 6
#define KFI_PROFILE_LINUX_MINOR 1
#define KFI_PROFILE_ENFORCE_VERSION 1

#endif
