#!/usr/bin/env python3
"""Generate matching kernel and userspace configuration for private procfs."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import secrets
import sys
import uuid


CONFIG_VERSION = 1
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_-]{7,47}$")
INSTANCE_PATTERN = re.compile(r"^[A-Za-z0-9._-]{8,64}$")


def validate_name(value: str) -> str:
    if NAME_PATTERN.fullmatch(value) is None:
        raise ValueError(
            "proc name must be 8-48 characters and match "
            "[a-z][a-z0-9_-]*"
        )
    return value


def validate_instance_id(value: str) -> str:
    if INSTANCE_PATTERN.fullmatch(value) is None:
        raise ValueError(
            "instance ID must be 8-64 characters and contain only "
            "letters, digits, dot, underscore, or hyphen"
        )
    return value


def render_header(name: str, instance_id: str) -> str:
    return f"""/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by scripts/gen_private_config.py. Do not commit this file. */
#ifndef KFI_PRIVATE_CONFIG_H
#define KFI_PRIVATE_CONFIG_H

#define KFI_PRIVATE_CONFIG_VERSION {CONFIG_VERSION}U
#define KFI_PRIVATE_PROC_NAME \"{name}\"
#define KFI_PRIVATE_BUILD_INSTANCE_ID \"{instance_id}\"

#endif
"""


def build_config(name: str, instance_id: str) -> dict[str, object]:
    return {
        "config_version": CONFIG_VERSION,
        "endpoint": f"proc:/proc/{name}/{name}",
        "instance_id": instance_id,
        "proc_name": name,
    }


def write_text(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f"{path.name}.{secrets.token_hex(4)}.tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path("kernel/generated/kfi_private_config.h"),
        help="generated kernel header",
    )
    parser.add_argument(
        "--user-config",
        type=pathlib.Path,
        help="optional userspace JSON endpoint configuration",
    )
    parser.add_argument("--name", help="explicit procfs node name")
    parser.add_argument("--instance-id", help="explicit build instance ID")
    args = parser.parse_args()

    try:
        name = validate_name(args.name or f"kfi_{secrets.token_hex(8)}")
        instance_id = validate_instance_id(
            args.instance_id or uuid.uuid4().hex
        )
        write_text(args.output, render_header(name, instance_id))
        config = build_config(name, instance_id)
        if args.user_config is not None:
            write_text(
                args.user_config,
                json.dumps(config, indent=2, sort_keys=True) + "\n",
            )
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    print(json.dumps(config, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
